### ISSUE TITLE
Function to get probability values of predicted output (like sklearn's predict_proba)?

### ISSUE THREAD

**Issue by a-sharma123** [huggingface/setfit#106]
Hi! I wanted to ask if there was an in-built function to get the probability value of predicted output from a classification task, something like predict_proba() from sklearn?

From what i understand currently the only way to get output is to run SetFitModel([text]), which works similar to sklearn predict().

**Comment by lewtun** [comment]
Hi @a-sharma123 you can get the probabilities by using the `SetFitModel.predict_proba([text])` method. Hope that helps :)
