### ISSUE TITLE
Question regarding framework

### ISSUE THREAD

**Issue by sersoage** [huggingface/setfit#113]
Is it possible to just used the fine tuned model to just do encoding? Like the original version of setfit? If possible could you pls let me know how? Thanks in advance

**Comment by lewtun** [comment]
Hi @sersoage if I understand correctly, you'd like to extract the embeddings from a fine-tuned `SetFitModel` right?

In that case you could use `SetFitModel.model_body.encode(inputs)`

**Comment by sersoage** [comment]
Thanks!

**Comment by sersoage** [comment]
Closing
