### ISSUE TITLE
How to take advantage of Mac M1 GPUs?

### ISSUE THREAD

**Issue by secastro** [huggingface/setfit#116]
More than an issue, this is a request for help.

Do you have advice on how to take advantage of the Mac M1 Pro GPU for training a model, assuming the underlying Torch implementation provides support?

There are some tutorials on how to use Torch with the MPS driver, but I'm not sure how to signal SetFit to use a specific GPU.

**Comment by zachschillaci27** [comment]
Any updates on this? What's needed to integrate support for `mps`? I'm happy to help as needed.

**Comment by turian** [comment]
@secastro @zachschillaci27 https://github.com/UKPLab/sentence-transformers/issues/1736 solves it

**Comment by joel-odlund** [comment]
MPS is supported by sentence-transformers since https://github.com/UKPLab/sentence-transformers/pull/2342

**Comment by tomaarsen** [comment]
Indeed! As of Sentence Transformers v2.3.0 it should now automatically select MPS as the default device if relevant.
```
pip install -U sentence_transformers
```

- Tom Aarsen
