### ISSUE TITLE
Predict method problem

### ISSUE THREAD

**Issue by doubianimehdi** [huggingface/setfit#122]
Hi, I'm trying to run the predict method on a dataframe text column and I have the following message :
this is the code : df_ri_manclassif['predicted']= model(df_ri_manclassif['global_text'].to_list())
this is the message : ---------------------------------------------------------------------------
NotFittedError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7856/2981536964.py in <module>
----> 1 df_ri_manclassif['predicted']= model(df_ri_manclassif['global_text'].to_list())

c:\Users\doub2420\AppData\Local\Programs\Python\Python39\lib\site-packages\setfit\modeling.py in __call__(self, inputs)
     60     def __call__(self, inputs):
     61         embeddings = self.model_body.encode(inputs)
---> 62         return self.model_head.predict(embeddings)
     63 
     64     def _save_pretrained(self, save_directory):

c:\Users\doub2420\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_base.py in predict(self, X)
    445             Vector containing the class labels for each sample.
    446         """
--> 447         scores = self.decision_function(X)
    448         if len(scores.shape) == 1:
    449             indices = (scores > 0).astype(int)

c:\Users\doub2420\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_base.py in decision_function(self, X)
    425             this class would be predicted.
    426         """
--> 427         check_is_fitted(self)
    428 
    429         X = self._validate_data(X, accept_sparse="csr", reset=False)
...
-> 1345         raise NotFittedError(msg % {"name": type(estimator).__name__})
   1346 
   1347 

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

Can you help ? Thank you !

**Comment by bilalghanem** [comment]
Are you sure that you loaded the trained model?
Also, you don't need to use `.predict`.  Just follow their example:
`preds = model(["i loved the spiderman movie!", "pineapple on pizza is the worst 🤮"])
`

**Comment by doubianimehdi** [comment]
Yes, I just trained it before !!! also I tried ditching .predict and still not working ... I didn't upload to hub because I don't want to ...

**Comment by doubianimehdi** [comment]
I'll post the code above this error tomorrow ...

**Comment by doubianimehdi** [comment]
here is the code : 

`#` takes a sentence-transformers model
#clf = SetFitClassifier("malteos/scincl")
model_id = `"sentence-transformers/allenai-specter"`

`# fine-tunes embeddings + trains logistic regression head
#clf.fit(docs, labels) 
#Trial 1 finished with value: 0.875 and parameters: {'learning_rate': 3.5528176658980156e-06, 'num_epochs': 4, 'batch_size': 8, 
# 'num_iterations': 80, 'seed': 14, 'max_iter': 79, 'solver': 'lbfgs', 'model_id': 'sentence-transformers/allenai-specter'}

from setfit import SetFitModel
from sentence_transformers.losses import CosineSimilarityLoss

model = SetFitModel.from_pretrained(model_id)

# model specfic hyperparameters
def model_init(params):
    params = params or {}
    max_iter = params.get("max_iter", 79)
    solver = params.get("solver", "lbfgs")
    num_iterations = params.get("num_iterations", 80)
    num_epochs = params.get("num_epochs", 4)
    seed = params.get("seed", 14)
    batch_size = params.get("batch_size", 32)
    model_id = params.get("model_id", "sentence-transformers/allenai-specter")
    learning_rate = params.get("learning_rate", 3.5528176658980156e-06)
    model_params = {
        "head_params": {
            "max_iter": max_iter,
            "solver": solver
        }
    }
    return SetFitModel.from_pretrained(model_id, **model_params)

from setfit import SetFitTrainer

trainer = SetFitTrainer(
    #model=model,
    train_dataset=train_dataset,
    eval_dataset=validate_dataset,
    model_init=model_init,
    column_mapping={"global_text": "text", "score": "label"},
)`

`trainer.train()`

`metrics = trainer.evaluate()
metrics`

**Comment by doubianimehdi** [comment]
Someone ? Please Help ! I'm stuck !!!

**Comment by tomaarsen** [comment]
Hello @doubianimehdi,

I've tried to reformat your code to be reproducible, but I am unable to. I've added my own dataset loading at the top to get this to run:
```python
from datasets import load_dataset

from setfit import sample_dataset


# Load a dataset from the Hugging Face Hub
dataset = load_dataset("sst2")

# Simulate the few-shot regime by sampling 8 examples per class
train_dataset = sample_dataset(dataset["train"], label_column="label", num_samples=8)
validate_dataset = dataset["validation"]

### End of custom code to get the dataset to work


# takes a sentence-transformers model
# clf = SetFitClassifier("malteos/scincl")
model_id = "sentence-transformers/allenai-specter"

# fine-tunes embeddings + trains logistic regression head
# clf.fit(docs, labels)
# Trial 1 finished with value: 0.875 and parameters: {'learning_rate': 3.5528176658980156e-06, 'num_epochs': 4, 'batch_size': 8,
#'num_iterations': 80, 'seed': 14, 'max_iter': 79, 'solver': 'lbfgs', 'model_id': 'sentence-transformers/allenai-specter'}

from setfit import SetFitModel
from sentence_transformers.losses import CosineSimilarityLoss

model = SetFitModel.from_pretrained(model_id)
# model specfic hyperparameters


def model_init(params):
    params = params or {}
    max_iter = params.get("max_iter", 79)
    solver = params.get("solver", "lbfgs")
    num_iterations = params.get("num_iterations", 80)
    num_epochs = params.get("num_epochs", 4)
    seed = params.get("seed", 14)
    batch_size = params.get("batch_size", 32)
    model_id = params.get("model_id", "sentence-transformers/allenai-specter")
    learning_rate = params.get("learning_rate", 3.5528176658980156e-06)
    model_params = {"head_params": {"max_iter": max_iter, "solver": solver}}
    return SetFitModel.from_pretrained(model_id, **model_params)


from setfit import SetFitTrainer

trainer = SetFitTrainer(
    # model=model,
    train_dataset=train_dataset,
    eval_dataset=validate_dataset,
    model_init=model_init,
    column_mapping={"sentence": "text", "label": "label"},
)

trainer.train()

metrics = trainer.evaluate()
print(metrics)

```
Beyond that, I only changed the `column_mapping`. With this script I do not experience any issues:
```
***** Running training *****
  Num examples = 640
  Num epochs = 1
  Total optimization steps = 40
  Total train batch size = 16
Iteration: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:24<00:00,  1.66it/s]
Epoch: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:24<00:00, 24.06s/it] 
Applying column mapping to evaluation dataset
***** Running evaluation *****
{'accuracy': 0.5894495412844036}
```
The accuracy isn't great, but that isn't relevant for now. I'll close this for now, but feel free to reopen this. Please format your code correctly in comments the next time, otherwise it's really difficult for us to help you.

- Tom Aarsen
