### ISSUE TITLE
id2label and label2id setup for inference 

### ISSUE THREAD

**Issue by rjac-ml** [huggingface/setfit#124]
I have add the id2label and labnel2id top the pretrained model, I know this is a Sentence Transformer model but I dont know if there is a way to pass the label mapper to the head of the SetFitModel 

`model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2",num_labels=num_classes,id2label=id2label,label2id=label2id)
`

In that way in inference time we just call the SetFit Model

**Comment by lewtun** [comment]
Hey @rjac-ml indeed the current way we save the model isn't ideal because the `config.json` file is missing the `label2id` and `id2label` mappings. 

I'll add this when I get some time (unless you'd like to open a PR yourself, which is certainly welcome!)

**Comment by tomaarsen** [comment]
Closed via #439
