### ISSUE TITLE
I want to use F1 macro metric but can not set it.

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/setfit#128]
I want to use F1 macro to evaluate the model.
But I can only pass a string to name the metric.
For F1 I would have to add `average="macro"` to the `compute` call here:

https://github.com/huggingface/setfit/blob/2bc12c6e41c3241aced7f210185e447384ca1652/src/setfit/trainer.py#L303

What do you think? Did I miss anything?

I can contribute a PR if wanted...

**Comment by lewtun** [comment]
Hey @PhilipMay thanks for spotting this! There's a PR to fix this in #125

**Comment by PhilipMay** [comment]
> Hey @PhilipMay thanks for spotting this! There's a PR to fix this in #125

Ok cool. Thanks. Closing this now.
