### ISSUE TITLE
Redirect __call__ to predict in SetFitModel

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/setfit#136]
Hi,

imo because of dry principle this function:

https://github.com/huggingface/setfit/blob/7735e8e3b208edb8dfb549beb16e585453c5f44e/src/setfit/modeling.py#L61-L63

should just redirect to predict. Because of dry principle. Like this:

```
    def __call__(self, inputs):
        return self.predict(inputs)
```

I can provide a PR if wanted.

**Comment by lewtun** [comment]
Oh yes, this would be much better indeed!

**Comment by PhilipMay** [comment]
> Oh yes, this would be much better indeed!

PR is here: #142

**Comment by kgourgou** [comment]
Nice, looks like this can be closed. 👍

**Comment by PhilipMay** [comment]
PR is merged - closing.
