### ISSUE TITLE
Use pre-computed token embeddings as features

### ISSUE THREAD

**Issue by victorjmarin** [huggingface/setfit#141]
Thank you for sharing your work!

I would like to use pre-computed token embeddings `inputs_embeds` as opposed to relying on a tokenizer to generate `input_ids` from the column mapped to "text".

For context, my pipeline looks as follows:

1. Embed sequences with a transformer to obtain contextual embeddings of tokens.
2. For each sequence, keep embeddings for certain subsets of tokens.
3. Train classifier with SetFit using token embeddings from (2) as features.

I had to make some tweaks for this approach to work (including in [sentence-transformers](https://github.com/UKPLab/sentence-transformers)) so I was wondering if there is a simpler way I may be missing.

Thank you.

**Comment by PhilipMay** [comment]
Since SetFit is internaly using sentence-transformers I guess that it is even more difficult. Also see here:

https://github.com/huggingface/setfit/blob/43dbaf1a914a08ff8ef8ec836ddd51586d7881bb/src/setfit/modeling.py#L319
