### ISSUE TITLE
[FR] document usage of differentiable head

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/setfit#143]
Can you please document the usage of the differentiable head in the README.md?
Maybe by just giving a simple example?

Maybe @blakechi ?

**Comment by lewtun** [comment]
Hi @PhilipMay this is a good suggestion - thanks! At some point I might need to make proper docs since the README is getting rather long :)

**Comment by lewtun** [comment]
FYI I'm going to extend the notebooks to show this API as a way to show how everything works before the next release

**Comment by blakechi** [comment]
Hi @PhilipMay,

Agree, I should add some examples and maybe also share some empirical suggestions. I can refine the text to at least make this section shorter :)

How do you think? @lewtun

**Comment by tomaarsen** [comment]
Resolved via #149! Thanks again, @blakechi 🚀
