### ISSUE TITLE
Train my own dataset

### ISSUE THREAD

**Issue by LaurentClaessens** [huggingface/setfit#157]
I have a dataset as json with tree classes (0, 1, 2) given as json:
```
{
   "sentence 1": 0,
   "sentence 2": 0,
   "sentence 3": 0,
   "sentence 4": 1,
   "sentence 5": 1,
   "sentence 6": 1,
   "sentence 7": 1,
}
```
Question: how do I train such a dataset ? Do I have to create the `.arrow` file ? How to do that ?

The key line in the tutorial that I have to adapt is this one:
```
dataset = load_dataset("SetFit/SentEval-CR")
```

**Comment by LuketheDukeBates** [comment]
Hi Laurent!
I think you just need to convert your json file to a transformers dataset object.
For example, 
``` 
from datasets import load_dataset
dataset = load_dataset('json', data_files='my_file.json', field='data')
```
Source: https://huggingface.co/docs/datasets/v1.1.3/loading_datasets.html

Hope that helps.

**Comment by LaurentClaessens** [comment]
Thanks LuketheDukeBates. It makes the work.

Here is a "full" code if someone is interested.

In `ds.json`:
```
{
    "train": {
        "text": [ "I ate a banana", "I ate a dog" ],
        "label": [ 1, 0 ],
        "label_text": [ "positive", "negative" ]
    },
    "test": {
        "text": [ "I ate an apple", "I ate a pig" ],
        "label": [ 1, 0 ],
        "label_text": [ "positive", "negative"
        ]
    }
}
```
In the main python script:
```
    json_ds = # read the json file in a way in an other

    my_train = Dataset.from_dict(json_ds["train"])
    my_test = Dataset.from_dict(json_ds["test"])
    my_dataset = DatasetDict(train=my_train, test=my_test)

   train_dataset = my_dataset["train"]
   eval_dataset = my_dataset["test"]
```
At this point one can continue the example [in the README](https://github.com/huggingface/setfit).

**Comment by nickums** [comment]
Very nice suggestion, but the module Dataset in your code cannot be found

**Comment by nickums** [comment]
correction: found them:
    from datasets.arrow_dataset import Dataset
    from datasets.dataset_dict import DatasetDict
