### ISSUE TITLE
How to use max_length (number max of tokens) as an argument?

### ISSUE THREAD

**Issue by piegu** [huggingface/setfit#172]
Hi,

`max_length` is defined [here ](https://github.com/huggingface/setfit/blob/00aa8764282741b68cac4565d2f1553ecd995ae9/src/setfit/data.py#L239) with the value 32.

How to modify it?

Thank you.

**Comment by blakechi** [comment]
Hello @piegu , thank you for raising up this issue.

So the `max_length` will be set to the maximum possible length according to the `model_body` (`sentence-transformers`) you use. Please see [here](https://github.com/huggingface/setfit/blob/main/src/setfit/modeling.py#L252) for details.

Hope this resolve your issue. If not, I think we can add one more argument when initializing `SetFitModel` with an assert checking whether the `max_length` exceeds the acceptable length the `model_body` can handle.

**Comment by piegu** [comment]
Hi @blakechi,

Thank you for your reply.
However, I don't want to set `max_length` to the maximum possible length. I want to be able to set it to any value via an argument.

Example: texts in my dataset have a maximum of 128 tokens. Then, I want to be able to set this value as `max_length`.

Note: when using `transformers `from Hugging Face, I configure the `max_length` value in the tokenizer through the argument `max_length`.

**Comment by blakechi** [comment]
Sure, I think we can achieve it as what I mentioned here:

> Hope this resolve your issue. If not, I think we can add one more argument when initializing `SetFitModel` with an assert checking whether the given `max_length` exceeds the acceptable one the `model_body` can handle.

@lewtun  How do you think? I can open a PR for this 😀
