### ISSUE TITLE
Exporting fine tuned model to ONNX

### ISSUE THREAD

**Issue by vimal-b** [huggingface/setfit#174]
Hi Team,
Thanks for this wonderful library. 

A quick python package on top of setfit for exporting to onnx format.
## Installation
```sh
pip install setfitonnx
```
## How to Export
```python
from setfitonnx import convert_onnx

# Setfit Model directory
model_path = "/home/mysetfit-model"
# ONNX Output directory
output_dir = "/home/setfit-onnx-model"
# Convert to ONNX
convert_onnx(model_path=model_path,output_dir=output_dir)

```

**Comment by tomaarsen** [comment]
#156 has also added first-party support for exporting ONNX! Feel free to help us verify that it works as intended :)
