### ISSUE TITLE
Save Model Locally trainer.save_model()

### ISSUE THREAD

**Issue by pleonova** [huggingface/setfit#182]
First off, super excited about all this work! Also really appreciate the [youtube presentation](https://www.youtube.com/watch?v=8h27lV8v8BU) and the [blogpost](https://huggingface.co/blog/setfit), super insightful to read through. I went through the existing issues and couldn't find whether this an existing functionality:

Is there a way to save the model locally instead of pushing to the hub?
So in addition to this:
`trainer.push_to_hub(f"setfit-myowndataset-multilabel-example")`
be able to do this too:
`trainer.save_model("file-path/setfit-myowndatase-multilabel-example")`

**Comment by theainerd** [comment]
It would be nice to have something like that. Presently that throws an error.

**Comment by kgourgou** [comment]
You should be able to do `model.save(path_str)` as usual.

**Comment by kavya-pc** [comment]
It can be done by 
trainer.model._save_pretrained(save_directory=save_directory).

Here is the link to the solution where it has already been answered - https://github.com/huggingface/setfit/issues/102

**Comment by pleonova** [comment]
Thank you @kgourgou and @kgourgou, that worked!

**Comment by badi02** [comment]
then how to load it ????

**Comment by tomaarsen** [comment]
@badi02 
```python
from setfit import SetFitModel

model = SetFitModel.from_pretrained("my/model/path")
```
