### ISSUE TITLE
picking which GPU to run the model on

### ISSUE THREAD

**Issue by Faisal-Hajari** [huggingface/setfit#193]
Hello,
First, thanks for the great lib and great work. I was wondering if there is a way to pick which cuda device to run my model on ? tried to search for it but it seems to automatically detect and just pick.

**Comment by kgourgou** [comment]
This is something that should be exposed at the level of SetFit. 

Currently, a SentenceTransformer is initialized here:

https://github.com/huggingface/setfit/blob/5313939b638b57668a1b5a67ef600e54da221d9a/src/setfit/modeling.py#L325

If you look at the documentation of the [SentenceTransformers](https://www.sbert.net/docs/package_reference/SentenceTransformer.html#sentence_transformers.SentenceTransformer) constructor, there is an option to pass device info. 

I only have one GPU so I can't test it, but my guess is you can do something like: 

```python
st = SentenceTransfomer('some_model_name', device=your_device_id) # this is your local model or generic sentence transformer
setfit_model = SetFit(model_body = st, model_head = LogisticRegression()) # Logistic regression from sklearn
```
