### ISSUE TITLE
Getting class labels

### ISSUE THREAD

**Issue by Rispo997** [huggingface/setfit#195]
Hello, I did train a set fit model with the default sklearn head.
Now I want to start doing predictions with the model, but I don't want to take just the top prediction, but the top N.
So I guess the correct way is outputting the probabilities with:
`preds = model.predict_proba(["This is a sentence"])`
Then I would get an array of probabilities, and I take the top-N prob. But then how do I convert the indexes I get back to labels? Where is the mapping stored? 
Thank you.

**Comment by Rispo997** [comment]
They are stored under model_body. classes_

**Comment by isaldiviagonzatti** [comment]
Hi, @Rispo997. I know this is a bit late, but I am trying to access the labels with your method and get this error:
`model.model_body.classes_`
AttributeError: 'SentenceTransformer' object has no attribute 'classes_'

With  model2.model_head.classes_ I get an output but it's just numpy arrays without the labels.

Thanks

**Comment by tomaarsen** [comment]
You might have better luck with `model.labels`, that's where the classes are stored nowadays. Otherwise `model.model_head.classes_` can indeed also have labels, depending on if you're using a sklearn head (e.g. like the default `LogisticRegression`) and if your dataset contained string or integer labels.

- Tom Aarsen

**Comment by isaldiviagonzatti** [comment]
Thanks, @tomaarsen . model.labels returns none, while model.model_head.classes_ returns an array of integers so no way of going back to the string labels. Any idea? I used the LogisticRegression indeed.

**Comment by rishi-2893** [comment]
Hello, you can use `model.classifier_head.classes_` to get the list of ordered labels.
