### ISSUE TITLE
[Bug] AttributeError: 'numpy.float64' object has no attribute 'pop'

### ISSUE THREAD

**Issue by FaezeGhorbanpour** [huggingface/setfit#197]
Hi,

First of all, I would like to thank you for providing this great and useful library. 
The following libraries are installed with Python 3.9:
setfit==0.4.1
optuna==3.0.3
transformers==4.20.1

On my dataset, I wanted to run a hyperparameter search using setfit[optuna]. As my dataset is imbalanced, I changed the trainer's metric from accuracy to weighted f-score (using Scikit-learn's f-score function), but I received the following error:

`AttributeError: 'numpy.float64' object has no attribute 'pop'`

Here is the error log:
[setfit error.txt](https://github.com/huggingface/setfit/files/10050722/setfit.error.txt)

The following code shows how I implemented the code:

```
def f1_score_weigted(y_true, y_pred):
    return f1_score(y_true, y_pred, average='weighted')



trainer = SetFitTrainer(
    train_dataset=train_ds,
    eval_dataset=dev_ds,
    model_init=model_init,
    metric= f1_score_weigted,
)


best_run = trainer.hyperparameter_search(hp_space=hp_space, n_trials=5)
```

Could you please help me how I can fix this error? Thank you in advance for any suggestions you may have.

**Comment by tomaarsen** [comment]
The hyperparameter search implementation has a `compute_objective` parameter, which is an optional function that computes the objective to minimize or maximize from the metrics returned by the `evaluate` method. By default, this is the following method from HF Transformers:

https://github.com/huggingface/transformers/blob/cbb8a37929c3860210f95c9ec99b8b84b8cf57a1/src/transformers/trainer_utils.py#L212-L230

As you can see, it expects the `evaluate` output to be a dict containing at least the keys `eval_loss` and `epoch`. Because of your custom `metric`, the `evaluate` output is a `numpy.float64` instead, hence your error.

This can be resolved by supplying a custom `compute_objective`, which only needs to return its input value. As a result, this snippet ought to work:
```python
def f1_score_weighted(y_true, y_pred):
    return f1_score(y_true, y_pred, average='weighted')


trainer = SetFitTrainer(
    train_dataset=train_ds,
    eval_dataset=dev_ds,
    model_init=model_init,
    metric= f1_score_weighted,
)

best_run = trainer.hyperparameter_search(
    hp_space=hp_space, compute_objective=lambda x: x, n_trials=5
)
```

<details><summary>Full reproducible example</summary>

```python
from sklearn.metrics import f1_score
from datasets import load_dataset

from setfit import SetFitModel, SetFitTrainer, sample_dataset

# Load a dataset from the Hugging Face Hub
dataset = load_dataset("sst2")

# Simulate the few-shot regime by sampling 8 examples per class
train_ds = sample_dataset(dataset["train"], label_column="label", num_samples=8)
eval_ds = dataset["validation"]


def f1_score_weighted(y_true, y_pred):
    # This is another alternative solution, but I would recommend just going with the 
    # compute_objective approach:
    # return {
    #     "eval_loss": f1_score(y_true, y_pred, average="weighted"),
    #     "epoch": 0
    # }
    return f1_score(y_true, y_pred, average="weighted")


def model_init(params):
    params = params or {}
    max_iter = params.get("max_iter", 100)
    solver = params.get("solver", "liblinear")
    params = {
        "head_params": {
            "max_iter": max_iter,
            "solver": solver,
        }
    }
    return SetFitModel.from_pretrained(
        "sentence-transformers/paraphrase-albert-small-v2", **params
    )


def hp_space(trial):  # Training parameters
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-4, log=True),
        "num_epochs": trial.suggest_int("num_epochs", 1, 2),
        "batch_size": trial.suggest_categorical("batch_size", [4, 8, 16, 32, 64]),
        "seed": trial.suggest_int("seed", 1, 40),
        "num_iterations": trial.suggest_categorical("num_iterations", [2, 5]),
        "max_iter": trial.suggest_int("max_iter", 50, 300),
        "solver": trial.suggest_categorical(
            "solver", ["newton-cg", "lbfgs", "liblinear"]
        ),
    }


trainer = SetFitTrainer(
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    model_init=model_init,
    metric=f1_score_weighted,
    column_mapping={"sentence": "text", "label": "label"},
)

# `compute_objective` here is the fix!
best_run = trainer.hyperparameter_search(
    hp_space=hp_space, compute_objective=lambda x: x, n_trials=5
)
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

metrics = trainer.evaluate()
print(metrics)
```
</details>

- Tom Aarsen

**Comment by FaezeGhorbanpour** [comment]
My error has been resolved by your comment. Thanks.
