### ISSUE TITLE
Question : why is model_original_state  necessary?

### ISSUE THREAD

**Issue by Yongtae723** [huggingface/setfit#199]
In SetFitModel, self.model_original_state is defined, as you can see [here](https://github.com/huggingface/setfit/blob/main/src/setfit/modeling.py#L225:~:text=l2_weight%20%3D%20l2_weight-,self.model_original_state%20%3D%20copy.deepcopy(self.model_body.state_dict()),-def%20fit).

But I don't see this variable being used again. So I wonder why you define that.
Since self.model_original_state contains the weights of sentence transformers, which leads to a heavy model class, so if it is not necessary, we can delete it to make a light model.

Could you tell me your opinion?

Thank you.
I am looking forward to your reply.

Yongtae

**Comment by tomaarsen** [comment]
Hello!

A `model_original_state` variable is used a few times in the different [`scripts`](https://github.com/huggingface/setfit/tree/main/scripts/setfit), so perhaps it's a relic from converting the scripts into a larger repository?

I agree that it does not seem needed. I'll make a PR so the maintainers can easily accept this change, should they agree with us.

- Tom Aarsen

**Comment by Yongtae723** [comment]
@tomaarsen 
Hi Tom! I confirmed your PR!

Thank you for it!

Yongtae
