### ISSUE TITLE
[FR] Should add that this is only used when using `distance_metric = BatchHardTripletLossDistanceFunction.cosine_distance`

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/setfit#213]
https://github.com/huggingface/setfit/blob/fa1021d2355f0cb3a2c85732ee7ffe44b0cef0d1/src/setfit/trainer.py#L48

I can provide a PR l8er.

**Comment by tomaarsen** [comment]
Resolved via #215. Thanks Philip!
