### ISSUE TITLE
Error with predict_proba 

### ISSUE THREAD

**Issue by alejandrods** [huggingface/setfit#237]
Hello,

I am using the `SetFitHead` and when I try to get the probabilities using the function `predict_proba()`, I get this error:

```
model_setfit = SetFitModel.from_pretrained("/content/save_win_loss_tags_v2")
```

![Screen Shot 2022-12-15 at 17 03 46](https://user-images.githubusercontent.com/32141606/207909255-acfb02d2-f323-46a3-93c2-62c350d9f414.png)

Is this a bug? 

Thank you.

**Comment by tomaarsen** [comment]
This is indeed a bug, I'm afraid. #207 has been set up to prevent it, but it still has some issues of its own.
For now, a workaround is to call:
```python
model_setfit = SetFitModel.from_pretrained(...)
inputs = ["testing new sentence to get probs"]
embeddings = model_setfit.model_body.encode(
    inputs,
    normalize_embeddings=False,
    convert_to_tensor=True
)
probs = model_setfit.model_head.predict_proba(embeddings)
```
This is roughly what the `predict_proba` method does, with exception of the `convert_to_tensor=True`, which is the crux of the bug:
https://github.com/huggingface/setfit/blob/7e2ae638cfce1867e9663864936ad04761e41a13/src/setfit/modeling.py#L329-L331

- Tom Aarsen

**Comment by alejandrods** [comment]
@tomaarsen Thank you! I will close it.
