### ISSUE TITLE
Automatically execute `scripts/create_summary_table.py` to reproduce average scores from paper

### ISSUE THREAD

**Issue by danielkorat** [huggingface/setfit#246]
The script in `scripts/create_summary_table.py` must be used to reproduce SetFit / baseline results from the paper. It calculates per-dataset average over the 10 training splits and saves the summary table to a file. However, this is scripts is not mentioned anywhere in the repo. It will be nice if it can be run automatically at the end of each SetFit / baseline run.

**Comment by lewtun** [comment]
Thanks for catching this @danielkorat! Would you like to open a PR with the fix?

**Comment by tomaarsen** [comment]
I'm fine with this simply being a documentation change, too. Adding information about the script to https://github.com/huggingface/setfit/blob/main/scripts/setfit/README.md may be sufficient.
