### ISSUE TITLE
Visualize training loss

### ISSUE THREAD

**Issue by domitix** [huggingface/setfit#247]
Hi,
I've been using this package for days and I have carried out many experiments, but I have noticed that it is not possible to visualize the training loss or print out something that lets you know how the training is going. Is there a way to obtain this?

Thank you in advance for the reply and for the awesome work!

**Comment by tomaarsen** [comment]
Hello!

It is my understanding that this is not currently possible. As it stands, there is no callback support for the trainer.
That said, I can imagine that support for this will be added in the future.

- Tom Aarsen

**Comment by zachschillaci27** [comment]
As @tomaarsen said, there's not currently callback support for the `SetFit` trainer, but it should be fairly straightforward to implement as it's defined within the `fit` method of `SentenceTransformer` (see [here](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L590)). I currently have a PR ([#1753](https://github.com/UKPLab/sentence-transformers/pull/1753)) open on `sentence-transformers` to extend the logging functionality but it has yet to be merged.

**Comment by tomaarsen** [comment]
#439 will introduce logging functionality for e.g. Tensorboard and W&B to track training and evaluation losses. Keep an eye out, I intend to release in the coming week.

**Comment by tomaarsen** [comment]
Closed via #439
