### ISSUE TITLE
Obtaining score while predicting

### ISSUE THREAD

**Issue by ablegith** [huggingface/setfit#248]
I am new to using Setfit and I have a question that may be too obvious. I have fine-tuned a model for text classification with one label but multiple classes. Once the model is trained, I can predict the labels but I can't get the prediction score as I can with other Huggingface models (where, for each prediction, I get back the tuple with the label and the score), because the model.predict() function returns only the label. How could I get this tuple in Setfit? Thank you!

**Comment by tomaarsen** [comment]
Perhaps `model.predict_proba()` in addition to `model.predict()` is what you are after?

**Comment by ablegith** [comment]
@tomaarsen yeah, that worked, thank you so much!
