### ISSUE TITLE
if model head is nn.module, final classification layer is not trained.

### ISSUE THREAD

**Issue by Yongtae723** [huggingface/setfit#271]
so sorry for making the many issues...

during tacking #212, I found If we use nn.Module, the final classification layer is not trained. 

I think this is not the behavior you intended.

this is because [here](https://github.com/huggingface/setfit/blob/f777c2c60b270604dae0dc1db4eea815e8c9019d/src/setfit/trainer.py#L385).

could you confirm that this is what you intended?

**Comment by tomaarsen** [comment]
Hello,

Don't worry about the number of issues!
The current implementation of the SetFitTrainer only trains the SetFitHead classification layer after `trainer.unfreeze()` has been called. In short, the correct way of training the differentiable head right now is:
```python
# Train and evaluate
trainer.freeze() # Freeze the head
trainer.train() # Train only the body

# Unfreeze the head and freeze the body -> head-only training
trainer.unfreeze(keep_body_frozen=True)
# or
# Unfreeze the head and unfreeze the body -> end-to-end training
trainer.unfreeze(keep_body_frozen=False)

trainer.train(
    num_epochs=25, # The number of epochs to train the head or the whole model (body and head)
    batch_size=16,
    body_learning_rate=1e-5, # The body's learning rate
    learning_rate=1e-2, # The head's learning rate
    l2_weight=0.0, # Weight decay on **both** the body and head. If `None`, will use 0.01.
)
metrics = trainer.evaluate()
```
See also the second code block of the README. Note that it differs from training without the differentiable head, which is just done via
```python
trainer.train()
metrics = trainer.evaluate()
```

I introduced #265 which will make the normal approach with just one `trainer.train()` call the way to train, regardless of the model head. 

But until that is merged, only calling `trainer.train()` will exclusively train the model body. So, the more complex training approach must be used for the differentiable head.

- Tom Aarsen

**Comment by Yongtae723** [comment]
Oh, I see.

I understand train code is different from training without the differentiable head

Thank you for your kind and easily understandable explanation!

**Comment by Bourhano** [comment]
then according to what's said before, would this call train the whole model with a single run? or no, because the parameter `keep_body_frozen` is depricated when used with a differentiable head (cross-reference from another issue I saw but couldn't find rn)? Hence this will only train the header?

````
trainer = SetFitTrainer(...)
trainer.unfreeze(keep_body_frozen=False)
trainer.train()
