### ISSUE TITLE
`trainer.save_model()` doesn't work

### ISSUE THREAD

**Issue by anjanvb** [huggingface/setfit#273]
Hey folks, i couldn't get [`save_model`](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.Trainer.save_model) to work.

<img width="800" alt="Screen Shot 2023-01-15 at 11 25 55 AM" src="https://user-images.githubusercontent.com/84933469/212563151-9741d80e-0677-4114-b49d-8ed45a31fb76.png">

I am guessing `push_to_hub` isn't the only option we got, right? My trainer is 

```python
from setfit import SetFitModel, SetFitTrainer
from sentence_transformers.losses import CosineSimilarityLoss

# Load a SetFit model from Hub
model_id = "sentence-transformers/all-mpnet-base-v2"
model = SetFitModel.from_pretrained(model_id)

# Create trainer
trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    loss_class=CosineSimilarityLoss,
    metric="accuracy",
    batch_size=64,
    num_iterations=20, 
    num_epochs=1, 
)

# Train and evaluate
trainer.train()
metrics = trainer.evaluate()

```

**Comment by tomaarsen** [comment]
@anjanvb 
Hello!

I'm afraid that the SetFit `SetFitTrainer` differs from the Transformers Trainer, and so it does not have a `save_model` method (as you've noticed).
For saving a model, we recommend `SetFitModel.save_pretrained(directory)`. `SetFitModel` extends `PyTorchModelHubMixin`, which has the [`save_pretrained`](https://huggingface.co/docs/huggingface_hub/v0.11.0/en/package_reference/mixins#huggingface_hub.ModelHubMixin.save_pretrained) method.

So, to extend your script:
```python
from setfit import SetFitModel, SetFitTrainer
from sentence_transformers.losses import CosineSimilarityLoss

# Load a SetFit model from Hub
model_id = "sentence-transformers/all-mpnet-base-v2"
model = SetFitModel.from_pretrained(model_id)

# Create trainer
trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    loss_class=CosineSimilarityLoss,
    metric="accuracy",
    batch_size=64,
    num_iterations=20, 
    num_epochs=1, 
)

# Train and evaluate
trainer.train()
metrics = trainer.evaluate()

model.save_pretrained("my_model_directory")
# or equivalently:
# trainer.model.save_pretrained("my_model_directory")
```

I believe that via #269 we will soon add some documentation to the README regarding saving a model.

Hope that helps,

- Tom Aarsen

**Comment by anjanvb** [comment]
Got it, thanks. Yes, I've tried the `model.save_pretrained` and it worked. I also tried with `joblib` and that worked too.

```python
import joblib

joblib.dump(trainer, './model/cstom-setfit-model.joblib')
trainer = joblib.load('./model/cstom-setfit-model.joblib')
trainer.model.predict(["text", "text"])

**Comment by tomaarsen** [comment]
Wonderful! Glad to hear it.
I'll close this, then!
