### ISSUE TITLE
Problem using distiluse models: forward() got an unexpected keyword argument 'token_type_ids' - possible fix

### ISSUE THREAD

**Issue by AleksanderObuchowski** [huggingface/setfit#287]
I have the following error while running SetFit with distiluse models (e.g. [this one](https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v1)):
When I try to fit the model I get

`TypeError: forward() got an unexpected keyword argument 'token_type_ids'`

From what I can see looking at the SetFitDataset the tokenizer always return the `token_type_ids` even if the Sentence Transformers model does not support them.

``` 
def __getitem__(self, idx: int) -> Tuple[TokenizerOutput, Union[int, List[int]]]:
        feature = self.tokenizer(
            self.x[idx],
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_token_type_ids=True,
        )
        label = self.y[idx]

        return feature, label
```
I think this could be changed to something like:

```
def __getitem__(self, idx: int) -> Tuple[TokenizerOutput, Union[int, List[int]]]:
        feature = self.tokenizer(
            self.x[idx],
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_token_type_ids=True if "token_type_ids" in self.tokenizer.model_input_names else False,
        )
        label = self.y[idx]

        return feature, label

```

And similarly, the `collate_fn` could be changed to output `token_type_ids` only if the model input expects it based on the `tokenizer.model_input_names`

I will be happy to make the PR if you think this is the right approach.

**Comment by tomaarsen** [comment]
Thank you for reporting! We would happily welcome your PR. To help out out already, I believe your solution can be simplified from:
```python
return_token_type_ids=True if "token_type_ids" in self.tokenizer.model_input_names else False,
```
to
```python
return_token_type_ids="token_type_ids" in self.tokenizer.model_input_names,
```

Furthermore, I would appreciate it if you could expand this fix to `return_attention_mask`, too. I assume most models require `attention_mask`, but some extra robustness is always appreciated.

- Tom Aarsen

**Comment by AleksanderObuchowski** [comment]
Thanks for the simplification, I created a PR https://github.com/huggingface/setfit/pull/288, I also changed the `collate_fn` form static method to normal method of the dataset as now the collator has to know what tokenizer is being used. I think it shouldn't cause any issues.

**Comment by harinisri2001** [comment]
HI @AleksanderObuchowski 
def load_embedding_model(model_path, normalize_embedding=True):
    return HuggingFaceEmbeddings(
        model_name=model_path,
        model_kwargs={'device': 'cpu'},
        encode_kwargs={'normalize_embeddings': normalize_embedding}
    )
  TypeError: DistilBertModel.forward() got an unexpected keyword argument 'token_type_ids'
I am also facing this issue. Can you please help me with this?
