### ISSUE TITLE
push_to_hub fails due to passing wrong number of positional arguments

### ISSUE THREAD

**Issue by nihiluis** [huggingface/setfit#290]
I get this error message: push_to_hub() takes 2 positional arguments but 12 were given

I trained a model and now am trying to push_to_hub, but the function throws an error on Colab. I'm on this version: setfit-0.5.0-py3-none-any.whl

The error occurs regardless of the string. Is this a bug, am I calling it wrong, is the README.md maybe outdated (that's where I took it from)?

![image](https://user-images.githubusercontent.com/24858082/214606504-7c4849ac-68af-4351-a52f-e9189d836e9c.png)

**Comment by ShianweiPang** [comment]
Have same problem here, looks like there is a bug. I even tried running their colab notebooks in the github.
![image](https://user-images.githubusercontent.com/63900253/214774815-a81b8678-d47b-41bc-a254-f1c7f54a6d56.png)

**Comment by tomaarsen** [comment]
Hello!

This seems to be related to a recent update from the `huggingface_hub`: [v0.12.0](https://github.com/huggingface/huggingface_hub/releases/tag/v0.12.0), which has overhauled its [`push_to_hub`](https://huggingface.co/docs/huggingface_hub/v0.12.0/en/package_reference/mixins#huggingface_hub.ModelHubMixin.push_to_hub) method.

Until we resolve this, you can get this to work again using
```
pip install huggingface_hub<0.12.0
```

- Tom Aarsen

**Comment by ShianweiPang** [comment]
> Hello!
> 
> This seems to be related to a recent update from the `huggingface_hub`: [v0.12.0](https://github.com/huggingface/huggingface_hub/releases/tag/v0.12.0), which has overhauled its [`push_to_hub`](https://huggingface.co/docs/huggingface_hub/v0.12.0/en/package_reference/mixins#huggingface_hub.ModelHubMixin.push_to_hub) method.
> 
> Until we resolve this, you can get this to work again using
> 
> ```
> pip install huggingface_hub<0.12.0
> ```
> 
> * Tom Aarsen

Thanks for the feedback provided. Meanwhile I used another alternative to have the model locally:
trainer.model.save_model("path_to_dir")
which solved my issue

**Comment by tomaarsen** [comment]
Wonderful, that works too!

**Comment by complycontrols** [comment]
How to load the model after saving it locally ?

**Comment by tomaarsen** [comment]
You can use
```python
SetFitModel.from_pretrained("path/to/local/save")
```

**Comment by anammari** [comment]
> > 
> > * Tom Aarsen
> 
> Thanks for the feedback provided. Meanwhile I used another alternative to have the model locally: `trainer.model.save_model("path_to_dir")` which solved my issue

There is no function save_model() in setfit v0.5.0:

`
import setfit
print(setfit.__version__)
trainer.model.save_model(model_name)
`

Output:
0.5.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 3
      1 import setfit
      2 print(setfit.__version__)
----> 3 trainer.model.save_model(model_name)

AttributeError: 'SetFitModel' object has no attribute 'save_model'

**Comment by tomaarsen** [comment]
You're very right! 
I would advise `trainer.model.save_pretrained(model_name)` or simply `model.save_pretrained(model_name)`, which saves the model locally, unless `push_to_hub` is set to True. See the documentation here: https://huggingface.co/docs/huggingface_hub/main/en/package_reference/mixins#huggingface_hub.ModelHubMixin.save_pretrained

Note that this isn't SetFit documentation, but instead documentation for `huggingface_hub` its `ModelHubMixin`, for which `SetFitModel` is a subclass. SetFit documentation is still a WIP: https://github.com/huggingface/setfit/issues/181.

- Tom Aarsen

**Comment by shariqfarooqui** [comment]
Hi there, is a fix for this yet? Downgrading `huggingface_hub`  does not work for me. I have the model saved locally where it runs fine, but I would like to upload it to share and use inference

**Comment by tomaarsen** [comment]
Hello @shariqfarooqui,

You can use `trainer.model.push_to_hub` using the [documentation](https://huggingface.co/docs/huggingface_hub/v0.13.1/en/package_reference/mixins#huggingface_hub.ModelHubMixin.push_to_hub) for your `huggingface_hub` version. Behind the scenes, the `trainer.push_to_hub` method also uses this functionality.

- Tom Aarsen

**Comment by shariqfarooqui** [comment]
> Hello @shariqfarooqui,
> 
> You can use `trainer.model.push_to_hub` using the [documentation](https://huggingface.co/docs/huggingface_hub/v0.13.1/en/package_reference/mixins#huggingface_hub.ModelHubMixin.push_to_hub) for your `huggingface_hub` version. Behind the scenes, the `trainer.push_to_hub` method also uses this functionality.
> 
> * Tom Aarsen

Hi Tom, thank you for the response. I have `huggingface_hub` version 0.12.1. I tried running the following code:
```
trainer.model.push_to_hub(
    repo_id=repo,
    commit_message=commit_message,
    private=True,
    branch="main",
    create_pr=False,
    token=hf_token,
)
```

but it returns a 
```
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

**Comment by tomaarsen** [comment]
Based on your screenshot alone, this feels like a bug on the `huggingface_hub` side, as it clearly seems to `os.path.join` a pathlib `Path` and a string. I'm afraid I don't have the bandwidth to debug it further at the moment.
