### ISSUE TITLE
Where can I set the code to train the setfit model on multiple GPUs?

### ISSUE THREAD

**Issue by Zoezoehooray** [huggingface/setfit#293]
I'm using the setfit trainer for my research paper. It requires a large amount of memory on computers and my computer always ran out of memory when I do the hyperparameters search. Currently, I have access to a computer with multiple GPUs installed. But the trainer still runs on only one GPUs. I did some research and saw other machine learning trainers have arguments like trainer(devices = 2,....).  I tried to insert this line in the setfit like trainer = SetFitTrainer(
    devices = 2,
    train_dataset=dataset,
    eval_dataset=dataset,
    model_init=model_init,
    column_mapping={"text_new": "text", "label_new": "label"},
), but apparently, it does not recognize it and reported errors. Anyone has any idea about setting the number of GPUs in the setfittrainer? Thank you soooooooooooooooooooooooooooooooooo much.

**Comment by tomaarsen** [comment]
Hello,

Multi GPU training is not supported, as SentenceTransformers (on which SetFit heavily relies) does not support it. See https://github.com/UKPLab/sentence-transformers/issues/311 for a related issue on that work. 

To add Multi-GPU support to SetFit, we must first add it to SentenceTransformers. I'll close this for now. A new similar issue can be opened once the aforementioned support for SentenceTransformers is added, but I'm not very hopeful that it will be.

- Tom Aarsen

**Comment by puppetm4st3r** [comment]
hi! @tomaarsen any news for this? best regards!

**Comment by twright8** [comment]
Yes, @tomaarsen I am also wondering considering sentence-transformers now support it

**Comment by puppetm4st3r** [comment]
also I have done a little experiment, train the basemodel with setfit, and then load the base model with sentencetransformer in order to fit a sentenceclassifier to replace the head of setfit, getting same accuracy and classifier results but with the plus that the final model complains the hugging face api, and also I can serve it like classification model with the high throutput TEI (Text embeddings inference) artifact from hugging face, solving a production and scalability issue(for me)

**Comment by gxcuit** [comment]
> also I have done a little experiment, train the basemodel with setfit, and then load the base model with sentencetransformer in order to fit a sentenceclassifier to replace the head of setfit, getting same accuracy and classifier results but with the plus that the final model complains the hugging face api, and also I can serve it like classification model with the high throutput TEI (Text embeddings inference) artifact from hugging face, solving a production and scalability issue(for me)

Hi, there,

Is there any code or instruction about how to train on multiple GPUs? Many thanks

**Comment by puppetm4st3r** [comment]
Only for the kind of experiment of I tryed (with a hybrid setfit/sentence transformer)

**Comment by gxcuit** [comment]
> Only for the kind of experiment I tried (with a hybrid setfit/sentence transformer)

I see. Besides, does the setfit support `resume_from_checkpoint` ? In issue #326 , it seems that this feature is not supported.

However, in my experiment, the checkpoint is saved. However, when I resume training, it trains from search, not resume. 

Any idea? Thanks
