### ISSUE TITLE
Module 'accuracy' doesn't exist on the Hugging Face Hub either

### ISSUE THREAD

**Issue by rdpulgar** [huggingface/setfit#301]
Hi,

I was running the code you provided in https://www.philschmid.de/getting-started-setfit and an error showed up in Trial 12 in module trainer.hyperparameter_search:

***** Running training *****
  Num examples = 640
  Num epochs = 1
  Total optimization steps = 80
  Total train batch size = 8
Iteration: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 80/80 [01:29<00:00,  1.12s/it]
Epoch: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:29<00:00, 89.52s/it]
[W 2023-02-06 03:01:05,419] Trial 12 failed with parameters: {'learning_rate': 1.405207941020111e-05, 'num_epochs': 1, 'batch_size': 8, 'num_iterations': 10, 'seed': 12, 'max_iter': 242, 'solver': 'newton-cg', 'model_id': 'sentence-transformers/all-mpnet-base-v2'} because of the following error: FileNotFoundError("Couldn't find a module script at /Users/rdpulgar/miniconda/accuracy/accuracy.py. Module 'accuracy' doesn't exist on the Hugging Face Hub either.").
Traceback (most recent call last):
  File "/Users/rdpulgar/miniconda/envs/torch-gpu/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/Users/rdpulgar/miniconda/envs/torch-gpu/lib/python3.10/site-packages/setfit/integrations.py", line 30, in _objective
    metrics = trainer.evaluate()
  File "/Users/rdpulgar/miniconda/envs/torch-gpu/lib/python3.10/site-packages/setfit/trainer.py", line 296, in evaluate
    metric_fn = evaluate.load(self.metric, config_name=metric_config)
  File "/Users/rdpulgar/miniconda/envs/torch-gpu/lib/python3.10/site-packages/evaluate/loading.py", line 702, in load
    evaluation_module = evaluation_module_factory(
  File "/Users/rdpulgar/miniconda/envs/torch-gpu/lib/python3.10/site-packages/evaluate/loading.py", line 652, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at /Users/rdpulgar/miniconda/accuracy/accuracy.py. Module 'accuracy' doesn't exist on the Hugging Face Hub either.
[W 2023-02-06 03:01:05,421] Trial 12 failed with value None.

can't figure out why it happened after so many other trials that run perfect.

Thank you.

Environment:

Apple MacBook Pro M2 Max 64GB 8 core.
OSX Ventura 13.2
Python 3.10.9
it was running in a conda environment

**Comment by tomaarsen** [comment]
Hello!

It seems that the program failed when trying to load the "accuracy" metric using:
```
metric_fn = evaluate.load(self.metric, config_name=metric_config)
```
where `self.metric` is `"accuracy"`. I suspect that there may have been a temporary outage that prevented https://huggingface.co/spaces/evaluate-metric/accuracy/blob/main/accuracy.py from being loaded. After all, this only happened after Trial 12, and it worked correctly the previous 11 times. I think this is a case of rerunning it.

I must say though, I've never had issues like this before myself.

I'll close it for now, but feel free to reopen if you think there's another issue at play!

- Tom Aarsen

**Comment by rdpulgar** [comment]
Thank you for your prompt response. Will run in again.

**Comment by freecui** [comment]
I have the same problem

**Comment by tomaarsen** [comment]
If the issue persists, then it may be worth raising a bug report on the [`evaluate`](https://github.com/huggingface/evaluate/) repository.

**Comment by rdpulgar** [comment]
I run again and it worked. If your issue happens again, try it overnight
