### ISSUE TITLE
Caching 🤗 Hub models in the CI tests

### ISSUE THREAD

**Issue by tomaarsen** [huggingface/setfit#307]
Hello!

Our [continuous integration test workflow](https://github.com/huggingface/setfit/blob/main/.github/workflows/tests.yml) is in charge of running our [test suite](https://github.com/huggingface/setfit/tree/main/tests) on all commits to the repository. However, these tests are slowed down by having to redownload the numerous Hugging Face Hub models that are used within.

A simple solution is to implement a cache using `actions/cache` that stores the models required by the tests. Ideally, this may help speed up the tests themselves. One approach is to (attempt to) load the cache as a step within the existing [`test_sampling`](https://github.com/huggingface/setfit/blob/main/.github/workflows/tests.yml#L14) job, whereas another idea is to implement a separate job that is required to have completed before the `test_sampling` job can start (via the `needs` keyword).

- Tom Aarsen

**Comment by EdAbati** [comment]
Hi @tomaarsen ,
I'd like to help with this.
