### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

### ISSUE THREAD

**Issue by maccarini** [huggingface/setfit#330]
I am getting the error while trying to save the model with `model.save_pretrained()` method.

![image](https://user-images.githubusercontent.com/22087162/224757792-7dd773da-8da9-4f07-9ed1-95e92e892c33.png)

**Comment by tomaarsen** [comment]
Hello @maccarini,

Thanks for reporting! I see now that this is causing test failures too. It must be caused by a recent update of `huggingface_hub`.
#332 tackles this issue.

- Tom Aarsen

**Comment by shamik-biswas-rft** [comment]
is this fixed in 
https://github.com/huggingface/setfit/releases/tag/v0.6.0
as the error still persists when i install setfit with `pip install git+https://github.com/huggingface/setfit.git@v0.6.0`

**Comment by shamik-biswas-rft** [comment]
Thanks for the reply.
