### ISSUE TITLE
Unable to save_pretrained model: TypeError: unsupported operand 

### ISSUE THREAD

**Issue by nihiluis** [huggingface/setfit#334]
This is the code I use:

`model.save_pretrained(os.path.join(model_path, "reviewsentiment-1403"))`

Arg that is passed `drive/MyDrive/Colab/Models/reviewsentiment-1403`

Not sure if I'm doing something wrong? Is this a sentencetransformer or setfit problem? Running on Colab.

Library versions used
```
 Downloading setfit-0.6.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 KB 1.3 MB/s eta 0:00:00
Collecting datasets
  Downloading datasets-2.10.1-py3-none-any.whl (469 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 39.6 MB/s eta 0:00:00
Collecting sentence-transformers>=2.2.1
  Downloading sentence-transformers-2.2.2.tar.gz 

Traceback

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <ipython-input-18-bc2978e2a0b5>:1 in <module>                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_deprecation.py:31 in inner_f       │
│                                                                                                  │
│    28 │   │   def inner_f(*args, **kwargs):                                                      │
│    29 │   │   │   extra_args = len(args) - len(all_args)                                         │
│    30 │   │   │   if extra_args <= 0:                                                            │
│ ❱  31 │   │   │   │   return f(*args, **kwargs)                                                  │
│    32 │   │   │   # extra_args > 0                                                               │
│    33 │   │   │   args_msg = [                                                                   │
│    34 │   │   │   │   f"{name}='{arg}'" if isinstance(arg, str) else f"{name}={arg}"             │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/huggingface_hub/hub_mixin.py:64 in save_pretrained        │
│                                                                                                  │
│    61 │   │   save_directory.mkdir(parents=True, exist_ok=True)                                  │
│    62 │   │                                                                                      │
│    63 │   │   # saving model weights/files                                                       │
│ ❱  64 │   │   self._save_pretrained(save_directory)                                              │
│    65 │   │                                                                                      │
│    66 │   │   # saving config                                                                    │
│    67 │   │   if isinstance(config, dict):                                                       │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/setfit/modeling.py:476 in _save_pretrained                │
│                                                                                                  │
│   473 │   │   return self.predict(inputs)                                                        │
│   474 │                                                                                          │
│   475 │   def _save_pretrained(self, save_directory: str) -> None:                               │
│ ❱ 476 │   │   self.model_body.save(path=save_directory, create_model_card=False)                 │
│   477 │   │   self.create_model_card(path=save_directory, model_name=save_directory)             │
│   478 │   │   joblib.dump(self.model_head, f"{save_directory}/{MODEL_HEAD_NAME}")                │
│   479                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/sentence_transformers/SentenceTransformer.py:370 in save  │
│                                                                                                  │
│   367 │   │   for idx, name in enumerate(self._modules):                                         │
│   368 │   │   │   module = self._modules[name]                                                   │
│   369 │   │   │   if idx == 0 and isinstance(module, Transformer):    #Save transformer model    │
│ ❱ 370 │   │   │   │   model_path = path + "/"                                                    │
│   371 │   │   │   else:                                                                          │
│   372 │   │   │   │   model_path = os.path.join(path, str(idx)+"_"+type(module).__name__)        │
│   373                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

**Comment by tomaarsen** [comment]
No worries! Very understandable :)
