### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by lenhhoxung86** [huggingface/setfit#339]
I used the following model init:

```
    model = SetFitModel.from_pretrained(
        "sentence-transformers/paraphrase-mpnet-base-v2",
        multi_target_strategy="one-vs-rest",
        use_differentiable_head=True,
        head_params={"out_features": len(categories)},
    )
```

And it threw the following error in the evaluation step (training was fine):

```
***** Running evaluation *****
Traceback (most recent call last):
  File "fewshot_classify_notes_multilabel_kfold.py", line 113, in <module>
    metrics = trainer.evaluate()
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/setfit/trainer.py", line 424, in evaluate
    return self.metric(y_pred, y_test)
  File "fewshot_classify_notes_multilabel_kfold.py", line 68, in compute_metrics
    predictions = predictions.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

If the model is initialized as follows:

```
    model = SetFitModel.from_pretrained(
        "sentence-transformers/paraphrase-mpnet-base-v2",
        multi_target_strategy="one-vs-rest"
    )
```

it worked without a problem.

How do I solve it?

**Comment by tomaarsen** [comment]
In your custom `compute_metrics` method, line 68 of `fewshot_classify_notes_multilabel_kfold.py`, the `predictions` tensor is still on the GPU, meaning that you must first move it to the CPU before you can convert it to numpy (as numpy isn't possible on the GPU).

As shown in the TypeError, you must first use `predictions.cpu().numpy()`. 
There is a chance that you'll encounter a similar error afterwards, perhaps complaining about "detaching". This refers to how the `predictions` tensor may still be "attached" to the computational gradient graph. If so, you can use `predictions.detach().cpu().numpy()`.

I hope that helps!

- Tom Aarsen

**Comment by lenhhoxung86** [comment]
It works, thanks.
So in two settings, the first time the `predictions` is on cpu and the second time the `predictions` is on gpu.
I would suggest to put `predictions` always on either cpu or gpu.

**Comment by tomaarsen** [comment]
I agree, that would be an improvement. I'll try to find some time for this.
