### ISSUE TITLE
Training a ternary Classifier: "Average" setting for Metrics "precision", "recall" and "f1"

### ISSUE THREAD

**Issue by stefantrapp** [huggingface/setfit#345]
Hi,
I trained a **ternary classifier** using SetFit and wanted evaluate the metrics **"accuracy", "precision", "recall" and "f1"**. However, I got the following error for all of these metrics except "accuracy":

        ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

To be able to use **other average settings** I overwrote the "**SetFitTrainer**" class with "**MySetFitTrainer**" as follows, overwriting the "evaluate" method (most of it is copy & paste, except for the two "if-elsed" calls to "metric_fn.compute(...)"):

        logger = logging.get_logger(__name__)

        class MySetFitTrainer(SetFitTrainer):
            def __init__(self, **kwargs):
                super(MySetFitTrainer, self).__init__(**kwargs)
            
            def evaluate(self, average=None, **kwargs):
                self._validate_column_mapping(self.eval_dataset)
                eval_dataset = self.eval_dataset
            
                if self.column_mapping is not None:
                    logger.info("Applying column mapping to evaluation dataset")
                    eval_dataset = self._apply_column_mapping(self.eval_dataset, self.column_mapping)
            
                x_test = eval_dataset["text"]
                y_test = eval_dataset["label"]
            
                logger.info("***** Running evaluation *****")
                y_pred = self.model.predict(x_test)
            
                if isinstance(self.metric, str):
                    metric_config = "multilabel" if self.model.multi_target_strategy is not None else None
                    metric_fn = evaluate.load(self.metric, config_name=metric_config)
                    print("eval:", self.metric, average if average is not None else None)
                    if (self.metric == "accuracy"):
                        result = metric_fn.compute(predictions=y_pred, references=y_test)
                    else:
                        result = metric_fn.compute(predictions=y_pred, references=y_test, average=average)
                    print("eval:", result)
                    return result
            
                elif callable(self.metric):
                    return self.metric(y_pred, y_test)
            
                else:
                    raise ValueError("metric must be a string or a callable")
This works as expected and when passing in different values for  the average parameter the result is the following:
![grafik](https://user-images.githubusercontent.com/50543708/230732110-4e68eeb2-6217-4c3d-b827-a1f0c666d3cd.png)
**My question is: For average "micro" in row 1 all metrics give the identical value (i.e. 0.724138). Is this a bug or expected behavior?** This is unclear to me. Help is appreciated. Thanks and best regards,
Stefan

**Comment by stefantrapp** [comment]
Hi Tom, thanks for your answer.
I found the following:

**https://scikit-learn.org/stable/modules/model_evaluation.html#multiclass-and-multilabel-classification**

"In a multiclass and multilabel classification task, the notions of precision, recall, and F-measures can be applied to each label independently. [...] **Note that if all labels are included, “micro”-averaging in a multiclass setting will produce precision, recall and F that are all identical to accuracy.** Also note that “weighted” averaging may produce an F-score that is not between precision and recall."

To be honest, I did not understand the explanation why this is the case, but at least it seems to be expected behavior. ;-)
Stefan

**Comment by tomaarsen** [comment]
Wonderful! I'm glad you've found the explanation, even though it's still a bit vague. Perhaps some studying of the micro-recall/precision/f1 functions will help with your understanding.

- Tom Aarsen

**Comment by Quantisan** [comment]
For anyone coming to this problem from search, this is fixed already. You just need to pass in a `metric_kwargs` to your `Trainer`.

```
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_dataset,
        metric="recall",
        # Ref for average parameter https://scikit-learn.org/stable/modules/model_evaluation.html#from-binary-to-multiclass-and-multilabel
        metric_kwargs={"average": "weighted"},
    )
```
