### ISSUE TITLE
How to run inference with torchscript?

### ISSUE THREAD

**Issue by giwook-david** [huggingface/setfit#346]
I trained model with setfit and tried to run inference with torchscript.
Based on [this link](https://huggingface.co/docs/transformers/torchscript), I tried but failed.
Let me share my trial

```
from setfit import SetFitModel
import torch

model_name = "sentence-transformers/all-mpnet-base-v2"
model = SetFitModel.from_pretrained(model_name)

def predict_fn(sentence):
      embedding = model.model_body.encode(sentence)
      return model.model_head.predict(embedding) # actually this function is almost same with SetFitModel.predict

sample_text = "This is test message"
preprocessed_input = predict_fn([sample_text])

traced_model = torch.jit.trace(predict_fn, (preprocessed_input, ))
```

Any opinion is welcome

**Comment by tomaarsen** [comment]
By default, the SetFit `model_head` is a `LogisticRegression` instance, which deals with numpy arrays. Understandably, torchscript won't work with that. Furthermore, `SetFitModel` is not a subclass of `nn.Module`, it doesn't have a `forward` method and it doesn't take torch Tensors as input in the prediction step.

In conclusion, you could probably rewrite the library to get this to work, but it'll be more work than it's worth.
I'll close this for now, as I don't suspect that we'll explicitly implement support for torchscript.

- Tom Aarsen
