### ISSUE TITLE
Massive Text Embedding Benchmark (MTEB) Leaderboard

### ISSUE THREAD

**Issue by vahuja4** [huggingface/setfit#367]
https://huggingface.co/spaces/mteb/leaderboard

Can we use all of these with setfit?

**Comment by tomaarsen** [comment]
I'm afraid not all of them, but the majority, yes. The `instruction` models that use `InstructorEmbedding` won't work. 

Beyond that, the ones that directly use `sentence-transformers` do work (e.g. https://huggingface.co/Muennighoff/SGPT-5.8B-weightedmean-msmarco-specb-bitfit) or ones that don't specify often work (e.g. https://huggingface.co/intfloat/e5-base, e.g. this one gets 81.6% accuracy on 8-shot [banking77](https://huggingface.co/datasets/banking77)).

It would be very interesting to see whether someone could implement InstructionEmbedding with SetFit - it should be relatively straight forward. I think that "InstructionSetFit" could be stronger than SetFit.

- Tom Aarsen

**Comment by kishorenc** [comment]
@tomaarsen 

Do you have any benchmarks on SetFit's performance on retrieval tasks (e.g. semantic search on query / document pairs)? For e.g. the `e5` family of models perform very well on retrieval.
