### ISSUE TITLE
Storing and Loading SetFit Model in Binary Format

### ISSUE THREAD

**Issue by joaopfp** [huggingface/setfit#371]
Hello, I am currently using SetFit in my project and I am impressed by its results. However, I would like to know how can I store and load the model in binary format. Thank you

**Comment by tomaarsen** [comment]
Hello!

You can save the model using `model.save_pretrained("path/to/local/dir")` and then load it again using `SetFitModel.from_pretrained("path/to/local/dir")`. This first command will save a bunch of files, and most importantly a `pytorch_model.bin` file with all of the model weights.

- Tom Aarsen

**Comment by joaopfp** [comment]
Great. Considering I have the pytorch_model.bin file with all the model weights, I would like to know how to run inference on texts. Thank you for your time.

**Comment by tomaarsen** [comment]
You can directly perform inference on texts by calling the model:
```python
model = SetFitModel.from_pretrained("path/to/local/dir")
predictions = model(["i loved the spiderman movie!", "pineapple on pizza is the worst 🤮"])
```
This is equivalent to using `model.predict(["i loved the spiderman movie!", ...])`, which you can also use.

- Tom Aarsen
