### ISSUE TITLE
Resolving confusion between fine-grained classes

### ISSUE THREAD

**Issue by vahuja4** [huggingface/setfit#374]
My dataset has 131 classes. Some of them are fine-grained, for example:

- Flag fraud on the account -> **Open Dispute**
- Find out if there is a fraud hold on my debit card ->**Dispute Inquiry**

The model is getting confused between such classes. I have roughly 20 samples per class in my dataset and I am using `mpnet-base-v2` with `num_iterations=25`.  Is there a way to specify which classes to draw the negative samples from given a positive class? Should I just add more data into the confusing classes?

**Comment by tomaarsen** [comment]
Hello!

There is no way to specify which classes should be used to draw negative samples from. These similar cases are definitely tricky. More training data for the disputing classes in particular may certainly help, but I suspect that it will continue to struggle somewhat to distinguish them, as they are quite similar in nature. 

Another alternative approach (which I'm sure you've already considered) would be to separate the problem into multiple SetFit models by grouping the fine-grained labels. If a fine-grained label is then chosen, a second SetFit model is applied to distinguish the cases further. This second model could be trained on only the problematic fine-grained classes, and this model should be able to discern the differences between the classes much more effectively.
That said, I understand the negative latency consequences.

- Tom Aarsen
