### ISSUE TITLE
shared memory

### ISSUE THREAD

**Issue by lsmith77** [huggingface/setfit#387]
When using Gunicorn there is an issue with PyTorch in relation to the gevent handler that prevents using `preload` to fork the workers after the models have been loaded into memory.

There is a workaround for this https://stackoverflow.com/questions/68935072/how-to-ram-efficiently-load-spacy-models-into-fastapi-with-gunicorn

This work around requires calling `model.eval()` and `model.share_memory()`. These functions however do not seem to be available on `SetFitModel` instances.

**Comment by tomaarsen** [comment]
Hello!

You can access the PyTorch model using `model.model_body`. This should have the `model.eval()` and `model.share_memory()` available. 

- Tom Aarsen
