### ISSUE TITLE
gradient_accumulation_steps

### ISSUE THREAD

**Issue by JRlbktBQLR** [huggingface/setfit#391]
Is it possible to pass certain transformer Trainer() parameters like gradient_accumulation_steps or fp16=True in order to avoid out of memory issue ?

**Comment by tomaarsen** [comment]
Hello!

I'm afraid this is not currently possible, as the [SentenceTransformers](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L575) that we rely on don't support either.

In the future I'd like to deprecate https://github.com/UKPLab/sentence-transformers and use our own variant. That way, we can use gradient accumulation and fp16/bf16, etc.

- Tom Aarsen
