### ISSUE TITLE
TypeError when running inference

### ISSUE THREAD

**Issue by joaopfp** [huggingface/setfit#394]
My training code looks like the following:

```
model_subcategories = SetFitModel.from_pretrained("all-minilm-l6-v2")

trainer_subcategories = SetFitTrainer(
    model=model_subcategories,
    train_dataset=ds_train_sub,
    eval_dataset=ds_test_sub,
    loss_class=CosineSimilarityLoss,
    batch_size=8,
    column_mapping={"processed text": "text", "subcategory": "label"},
    num_iterations=20, 
    num_epochs=1 
)

trainer_subcategories.train()
model_subcategories.to("cpu")
model_subcategories.save_pretrained('SetFitModel')
```

However, when I open the trained model and try to run inference using the following code:

```
from setfit import SetFitModel

model = SetFitModel('SetFitModel')
model(['Text Example'])
```

I run into the following error:
```
TypeError: encode() takes at most 2 arguments (3 given)
```

**Comment by tomaarsen** [comment]
Hello!

This `encode` method is called here:
https://github.com/huggingface/setfit/blob/b503c0b80b1fce800380e8e9092ab0ad14ae8889/src/setfit/modeling.py#L430-L434

with the three arguments. `model_body` is a `SentenceTransformer` instance from UKPLab's sentence-transformer library:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L111

I suspect that perhaps you're using an outdated version of that package. Could you check `pip show sentence_transformers`. I'm successfully using 2.2.1 myself.

- Tom Aarsen

**Comment by joaopfp** [comment]
When using the version 2.2.1 of sentence-transformers the error still persists.

**Comment by tomaarsen** [comment]
What version of SetFit are you using? I'll try to chase this down when I have some more time.

**Comment by joaopfp** [comment]
Right now I am using the 0.6.0 version

**Comment by MattiL** [comment]
I still get this error with setfit 0.7.0 and sentence_transformers 2.2.2.

**Comment by MattiL** [comment]
Replacing

model = SetFitModel('SetFitModel')

with

model = SetFitModel.from_pretrained('SetFitModel')

fixed this for me.

**Comment by tomaarsen** [comment]
Ohh, that's exactly it. Well spotted @MattiL.
