### ISSUE TITLE
'MPNetModel' object has no attribute 'has_differentiable_head' error

### ISSUE THREAD

**Issue by MikeAgb** [huggingface/setfit#414]
**versions:**
transformers==4.28.0 
setfit==0.7.0
sentence_transformers==2.2.2 

**Error:**
    340 batch_size = batch_size or self.batch_size
    341 learning_rate = learning_rate or self.learning_rate
--> 343 if not self.model.has_differentiable_head or self._freeze:
    344     # sentence-transformers adaptation
    345     if self.loss_class in [
    346         losses.BatchAllTripletLoss,
    347         losses.BatchHardTripletLoss,
   (...)
    350         SupConLoss,
    351     ]:
    352         train_examples = [InputExample(texts=[text], label=label) for text, label in zip(x_train, y_train)]

Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'MPNetModel' object has no attribute 'has_differentiable_head'

**Steps to reproduce**

from transformers import AutoModel
from sentence_transformers.losses import CosineSimilarityLoss
from setfit import SetFitModel, SetFitTrainer

local_path = './sentence-transformers'
model = AutoModel.from_pretrained(local_path)

trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    loss_class=CosineSimilarityLoss,
    batch_size=batch_size,
    num_iterations= num_iterations,
    num_epochs=num_epochs,
    column_mapping={"query": "text", "labels": "label"},
)
trainer.train()

**Comment by tomaarsen** [comment]
Hello!

Apologies for the slow response. To load a SetFit model, you must use `SetFitModel.from_pretrained(model_path_or_id)`, not `AutoModel.from_pretrained(...)`. The script should work with that one small adjustment.

I'll close this for now, but feel free to reopen or make a new issue if you have other questions.

- Tom Aarsen
