### ISSUE TITLE
Passing multiple evaluation metrics to SetFitTrainer

### ISSUE THREAD

**Issue by fhamborg** [huggingface/setfit#417]
Hi there, after reading the docs I find that one can easily get the f1 score or accuracy by passing the respective string as the `metric` argument to the trainer. However, how can I get both or even other metrics, such as f1_per_class?

Thanks :)

**Comment by tomaarsen** [comment]
Hello!

You can also pass a function as the `metric` to `SetFitTrainer`! It should accept two arguments: `y_pred`, `y_test`. Then you can do your own calculations for f1 score, accuracy, precision, recall, etc. etc., and return it as a dictionary of metric keys to values. That  should give you the flexibility that you're after!

Hope this helps, I'll close this for now.

- Tom Aarsen
