### ISSUE TITLE
[Q] How to examine correct/wrong predictions in trainer.evaluate()

### ISSUE THREAD

**Issue by youngjin-lee** [huggingface/setfit#423]
Hello,

After doing "metrics = trainer.evalute()" as shown in the example code, is there a way to examine which rows in the evaluation data set were predicted correctly?

Thanks!

**Comment by tomaarsen** [comment]
Currently that is not possible. However, you could call `model.predict` with the evaluation data to get the predictions. Alongside the known correct annotations, you can write some code to filter for only the correct/incorrect cases. That way you can manually observe the mistakes that the model is making.

- Tom Aarsen

**Comment by youngjin-lee** [comment]
Thank you Tom.
