### ISSUE TITLE
Training head with different dataset set than body

### ISSUE THREAD

**Issue by sanchez5674** [huggingface/setfit#430]
Is it possible to train the head with a different dataset than the body? I'm trying to understand the behavior of the logistic regression if new data samples become available. Thus, I'd like to train the body once with the primary dataset. Then, add new samples to the primary dataset to see how the head behaves. Right now, I'm doing that exercise training body and head with the new data but everything feels somewhat unstable in the sense that the model will learn to classify the new samples but forget some of the older ones in the process. Thanks.

**Comment by kgourgou** [comment]
Hello,

Of course, in the standard setup, the head is just an sklearn model (logistic regression), so you can use methods like `warm_start`.

Simply train your SetFit model, let's call it `model`, as normal, then extract the head with `model.model_head`, update it as you see fit, then replace it back into the SetFit model by `model.model_head = updated_model`. I think that should work. 

You may also find the `model.encode` (or `model.model_body.encode`, whichever works) useful after training to get embeddings with which to train your `model_head`.

**Comment by sanchez5674** [comment]
Hi, thanks for the response but I'm not 100% clear how to pass the new data to the head? I've looked around and I have not seen any examples. Right now, I'm doing the following but I'm not 100% sure it is correct. 

```
# create the model
model_s = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2",
                                                                     use_differentiable_head=True,)

trainer_s.SetFitTrainer(***)

# train body
trainer_s.train()

# freeze body and train the head
trainer_s.unfreeze(keep_body_frozen=True)

trainer_s.train(***)
```

To retrain the head with new data I keep the body frozen and change the training data and retrain

```
trainer_s.train_dataset = new_data_sample
trainer_s.train(***)


```

**Comment by kgourgou** [comment]
Apologies, I thought you weren't using a differentiable head. There may be more steps when the head is a PyTorch model.

**Comment by sanchez5674** [comment]
Can I then assume the code above is not correct? I have a small training sample that produces good results. However, when I add just one more item to the training sample my predictions change quite a bit. Some items that were true before become false and vice-versa. Thus, I would like to keep my embeddings frozen but retrain only the regression part with more and more data in order to minimize the "movement" described above.

**Comment by sanchez5674** [comment]
Thanks a lot. There's a small mistake: `X_new = model_s.model_body.encode(text_new)` but other than that it works great. Thanks!

**Comment by tomaarsen** [comment]
Thanks a bunch for helping answer this one @kgourgou!
