### ISSUE TITLE
Issues with deploying endpoint on sagemaker

### ISSUE THREAD

**Issue by miteshkotak** [huggingface/setfit#438]
Two questions?
1) setfitTrainer  class generate model.safetensors instead of pytorch mode , does anyone know why??

2)Until last month i was able deploy my model from s3 bucket to sagemaker endpoint with customer inference.py/

i didn't change anything just retrained the model and deployed the new endpoint now it throws error.
`
ValueError: ("You need to define one of the following ['audio-classification', 'automatic-speech-recognition', 'feature-extraction', 'text-classification', 'token-classification', 'question-answering', 'table-question-answering', 'fill-mask', 'summarization', 'translation', 'text2text-generation', 'text-generation', 'zero-shot-classification', 'conversational', 'image-classification', 'image-segmentation', 'object-detection'] as env 'HF_TASK'.", 403)`

i will greatly appreciate if someone can help here.

**Comment by miteshkotak** [comment]
Hi @tomaarsen, Many thanks for your prompt reply 
i tried two different ways.
- While saving model, passed a argument safe_serialization=False, which throws error .
- Tried downgrading Transformer version to ` transformers[sentencepiece,optuna]==4.20.0`  but it still outputs model.safetensors

**Comment by miteshkotak** [comment]
it's partially solved. i was able deploy endpoint on Hugging face  

Downgrading transformer==4.33.2 
which solved error with other class too e.g. trainer.evaluate (when using custom_metric) and trainer.push_to_hub 
Runs switfly

But deploying endpoint on  sagemaker it's still an issue.

 i will close this issue as it's sagemaker related. 

Many thanks @tomaarsen

**Comment by Overfitter** [comment]
@miteshkotak  - Were you able to resolve this SageMaker related issue?
@tomaarsen  - Do you have any guidance, whats the best way to deploy SetFit model on SageMaker?

Thanks for your help!!

**Comment by miteshkotak** [comment]
> @miteshkotak - Were you able to resolve this SageMaker related issue? @tomaarsen - Do you have any guidance, whats the best way to deploy SetFit model on SageMaker?
> 
> Thanks for your help!!

@Overfitter  in order to deploy custom inference handler on sagemaker , 
you need to create folder named `code`  

Add following two files within this folder

 -  `inference.py` with custom code for predicting label  
 -  `requirements.txt` with dependency as "setfit==1.0.3" 

keep the setfit version accordingly
