### ISSUE TITLE
ConstructorError when try to trainer.model._save_pretrained

### ISSUE THREAD

**Issue by LukasKriesch** [huggingface/setfit#458]
Hi,

I used setfit for training a model. When I want to save it calling `trainer.model._save_pretrained(path)` I receive the following error:

`ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:numpy.core.multiarray.scalar'
  in "<unicode string>", line 52, column 14:
          value: !!python/object/apply:numpy.core ... 
                 ^`
Thanks!

**Comment by tomaarsen** [comment]
Yes, for the time being, please convert the values in the dictionary to floats, and it should work again! Apologies for the inconvenience. 
For information, SetFit now creates model cards using the computed metrics, but it seems like it expects `evaluate` to always return a dictionary with string keys and integer/float/string values, i.e. nothing numpy or torch. I'll have to prepare a patch for this.

- Tom Aarsen
