### ISSUE TITLE
ABSA for Non-English Language

### ISSUE THREAD

**Issue by firqaaa** [huggingface/setfit#491]
Hi, we are aware that, up to now, most ABSA models have been developed for English, and they typically require the installation of the spaCy model for that language. However, it is observed that spaCy does not cover all languages. So, is it feasible to construct an ABSA model for languages with limited resources that are not supported by spaCy?

**Comment by kgourgou** [comment]
@firqaaa are you particularly interested in such models being fine-tuned with the setfit training paradigm? Your question seems to be a bit more general.

**Comment by firqaaa** [comment]
Yes, currently i want to build setfit for indonesian language but there's no spacy model available that spacy provided in their pipeline. so, is there any ways to build absa model without include the spacy model??

**Comment by tomaarsen** [comment]
Hello!

I'm afraid that the spaCy model is indeed required for SetFit ABSA. It is used throughout the codebase there, so we can't currently modify SetFit ABSA to use some other initial candidate selector.

That said, I see that you have been successful! 
* https://huggingface.co/firqaaa/indo-setfit-absa-bert-base-restaurants-aspect
* https://huggingface.co/firqaaa/indo-setfit-absa-bert-base-restaurants-polarity

I believe this is the first non-English SetFit ABSA model. Well done!

- Tom Aarsen

**Comment by firqaaa** [comment]
Hi @tomaarsen 

Thank you for the appreciation. Yes, you're correct; that's my work on SetFit ABSA for Bahasa. Although it was successful, there were still some improvements that I need to make, especially regarding the enhancement of the NER task in my own spaCy models for Bahasa and the accuracy of the model's polarity. Since it has been resolved, I will close this issue. Thank you!
