### ISSUE TITLE
Can we use Setfit just for finetuning ST Embedding model to create embeddings

### ISSUE THREAD

**Issue by kjoth** [huggingface/setfit#508]
Hello,

According to the documentation, SetFit is described as **"a model framework to efficiently train text classification models with surprisingly little training data."** Does this imply that using SetFit is only meaningful when applied to classification tasks, rather than generating embeddings? Or can we leverage SetFit to train a Sentence Transformer - Embedding model specifically for generating embeddings, without engaging in text classification?

https://huggingface.co/docs/setfit/en/conceptual_guides/setfit

**Comment by tomaarsen** [comment]
Hello!

Yes, this is completely possible. However, at some point it might make some more sense to directly use [Sentence Transformers](https://sbert.net/).

- Tom Aarsen

**Comment by kjoth** [comment]
Thanks @tomaarsen for clarifying. We conclude that it's suitable to utilize the Sentence Transformer for training Embedding models for embedding tasks and to employ SetFit for training Embedding models for classification tasks.
