### ISSUE TITLE
AttributeError: 'TrainingArguments' object has no attribute 'eval_strategy'

### ISSUE THREAD

**Issue by jayeshchoudhari** [huggingface/setfit#535]
Trying to run the example given in the [README](https://github.com/huggingface/setfit?tab=readme-ov-file) gives an AttributeError -- `'TrainingArguments' object has no attribute 'eval_strategy'`. However, there is no attribute 'eval_strategy' mentioned in the code.

**Comment by tomaarsen** [comment]
Hello!

You can either downgrade your `transformers` version, or use this as a workaround: https://github.com/huggingface/setfit/issues/512#issuecomment-2118679266

- Tom Aarsen

**Comment by jayeshchoudhari** [comment]
Thanks. That was a easy work around. 
I downloaded the transformers source code separately changed the variable `args.eval_strategy` to `args.evaluation_strategy` in `trainer_callback.py` :|.
