### ISSUE TITLE
Compatibility with ColBERT Models Trained with Pylate

### ISSUE THREAD

**Issue by abedkhooli** [huggingface/setfit#563]
Tried to use a ColBERT model trained using [Pylate](https://github.com/lightonai/pylate) since it was built on top of Sentence Transformers. The model loaded (`SetFitModel.from_pretrained`) but failed in `trainer.train()`:
`[/usr/local/lib/python3.10/dist-packages/sentence_transformers/losses/CosineSimilarityLoss.py](https://localhost:8080/#)`
`---> 76         embeddings = [self.model(sentence_feature)["sentence_embedding"] for sentence_feature in sentence_features]` 
`KeyError: 'sentence_embedding'` 
Are those models fully incompatible or there is a fix?

**Comment by tomaarsen** [comment]
I'm afraid those are fully incompatible. ColBERT models simply have different outputs than regular Sentence Transformer models.

- Tom Aarsen
