### ISSUE TITLE
Predict_Proba Output Tensor Mapping to Class Labels

### ISSUE THREAD

**Issue by ctandrewtran** [huggingface/setfit#565]
Hello!

I am classifying based on ~1000 different classes

I am interested in using predict_proba, then grabbing the top N predicted classes.

Is there a way to achieve this easily using what is available with setfit?

**Comment by ctandrewtran** [comment]
Closing with answer to help others-

np.argpartition(predict_proba_output, -n_wanted_predictions)[-n_wanted_predictions:]

**Comment by ctandrewtran** [comment]
Hmm- I am getting unreliable results.

![image](https://github.com/user-attachments/assets/9e33b09f-5cfe-4970-8d9a-238f3a5ce825)

**Comment by ctandrewtran** [comment]
Per the above example- np argmax on the output of predict_proba should return the same as predict, but that is not happening.

**Comment by krumeto** [comment]
If I understand your use case correctly, you might be looking for `model.model_head.classes_`:

Ugly example below:
```
probas = model.predict_proba(docs)

proba_dict = [dict(zip(model.model_head.classes_,p.numpy())) for p in probas]
predict_report = pd.DataFrame(proba_dict)
```

**Comment by ctandrewtran** [comment]
Hmm, just ran it and it gave TypeError: iteration over a 0-d array
