### ISSUE TITLE
How to save the model that is fitted 

### ISSUE THREAD

**Issue by techthiyanes** [huggingface/setfit#66]
Could you please share the ways to save the fitted model

**Comment by YaYaB** [comment]
You can save the model thanks to this
```
trainer.model._save_pretrained("./saved")
```
https://github.com/huggingface/setfit/blob/main/src/setfit/modeling.py#L55

**Comment by techthiyanes** [comment]
> You can save the model thanks to this
> 
> ```
> trainer.model._save_pretrained("./saved")
> ```
> 
> https://github.com/huggingface/setfit/blob/main/src/setfit/modeling.py#L55

Actually could you please guide us how to save the model after completing trainer.train().

In HF trainer, we have trainer.save_model() to save the models.

But this save_pretrained() method saves the model that's not fitted

**Comment by YaYaB** [comment]
The model_body is finetuned during the training and the model_head is trained. You can try `save_pretrained` before training and after training to verify that the files dumped are not the same. You can then load those with load_pretrained and make predictions to observe the differences too
The SetFitModel is baed on ModelHubMixin, in the doc it is specified that the save_pretrained method dumps the weights localy https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.ModelHubMixin.save_pretrained

**Comment by techthiyanes** [comment]
> > You can save the model thanks to this
> > ```
> > trainer.model._save_pretrained("./saved")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/huggingface/setfit/blob/main/src/setfit/modeling.py#L55
> 
> Thanks for responding my query. Actually could you please guide us how to save the model after completing trainer.train().
> 
> In HF trainer, we have trainer.save_model() to save the models.
> 
> But this save_pretrained() method saves the model that's not fitted

Thanks for your response.
Once i trained, I have used trainer.model._from_pretrained('/content/drive/MyDrive/saved') to load the model.
Predict &predict_proba are used it for prediction.

To load the model again, used simply model = SetFitModel.from_pretrained("/content/drive/MyDrive/saved") then able to predict & found the expected prediction. Thanks a lot.
