### ISSUE TITLE
Error when trying to run run_fewshot_multilabel.py

### ISSUE THREAD

**Issue by a-sharma123** [huggingface/setfit#68]
Hi! Congratulations on the work! I wanted to use this model for my multilabel task but I have an issue when trying to run the script for multilabel classification (run_fewshot_multilabel.py)
i get this error. 
`from setfit.modeling import LOSS_NAME_TO_CLASS, SetFitBaseModel, SKLearnWrapper, sentence_pairs_generation_multilabel
ImportError: cannot import name 'LOSS_NAME_TO_CLASS' from 'setfit.modeling'`
I went ahead and checked the file it was referring to (modeling.py) and there was no LOSS_NAME_TO_CLASS variable there.
Any help would be appreciated.

**Comment by lewtun** [comment]
Hey @a-sharma123 thanks for reporting this bug! It's definitely a side effect from a recent refactoring - I'll fix it ASAP.

**Comment by lewtun** [comment]
This is now fixed! Just FYI our scripts were designed with our paper in mind, so we assume the datasets exist under the `SetFit` org on the Hub. Another consideration is that we assume the multilabel datasets have been "flattened", with one column per class, e.g. https://huggingface.co/datasets/SetFit/go_emotions

**Comment by a-sharma123** [comment]
thanks for fixing the issue! I cloned the new repo and tried running the script, the model started running but after 5 mins the model stops and this error pops up.
`Traceback (most recent call last):
  File "C:\Users\myprofile\Documents\Codes\setfit\scripts\setfit\run_fewshot_multilabel.py", line 200, in <module>
    main()
  File "C:\Users\myprofile\Documents\Codes\setfit\scripts\setfit\run_fewshot_multilabel.py", line 186, in train_eval_all_datasets
    metrics = self.eval(classifier, test_data, metric)
  File "C:\Users\myprofile\Documents\Codes\setfit\scripts\setfit\run_fewshot_multilabel.py", line 153, in eval
    metric_fn = load(metric, config_name="multilabel")
  File "C:\Users\myprofile\AppData\Local\Programs\Python\Python310\lib\site-packages\evaluate\loading.py", line 702, in load
    evaluation_module = evaluation_module_factory(
  File "C:\Users\myprofile\AppData\Local\Programs\Python\Python310\lib\site-packages\evaluate\loading.py", line 652, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at C:\Users\myprofile\Documents\Codes\setfit\scripts\setfit\accuracy\accuracy.py. Module 'accuracy' doesn't exist on the Hugging Face Hub either.`
Any help would be hugely appreciated.
