### ISSUE TITLE
Implement trainer for distillation

### ISSUE THREAD

**Issue by lewtun** [huggingface/setfit#90]
In our paper, we used knowledge distillation to compress a SetFit model into a smaller student. This logic is currently implemented as a [script](https://github.com/huggingface/setfit/blob/main/scripts/setfit/run_fewshot_distillation.py), but it would be valuable to refactor this out to a `SetFitDistillationTrainer` that people can use in e.g. a Jupyter notebook.

cc @orenpereg

**Comment by tomaarsen** [comment]
Implemented via #166.
