### ISSUE TITLE
Multilabel Support

### ISSUE THREAD

**Issue by hanshupe** [huggingface/setfit#99]
What is the current status of multi label support? I saw a notebook for a multi label task here, but can't find it anymore. Can someone provide a working example for a multi label classification task? Thanks!

**Comment by lewtun** [comment]
Hi @hanshupe, we've just merged a notebook showing how SetFit works for multilabel cases: https://github.com/huggingface/setfit/blob/main/notebooks/text-classification_multilabel.ipynb

(I'll also update the README shortly)

Feel free to close this issue if that answers your question
